services:
  track-service:
    image: dawidwyskwarski/track-service:latest
    build:
      context: .
      dockerfile: ./track-service/Dockerfile
    env_file:
      - ./track-service/.env
    ports:
      - "8081:8080"
    networks:
      - overlay-network
    deploy:
      replicas: 4
      mode: replicated
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  tag-service:
    image: dawidwyskwarski/tag-service:latest
    build:
      context: .
      dockerfile: ./tag-service/Dockerfile
    env_file:
      - ./tag-service/.env
    ports:
      - "8082:8080"
    networks:
      - overlay-network
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  playlist-service:
    image: dawidwyskwarski/playlist-service:latest
    build:
      context: .
      dockerfile: ./playlist-service/Dockerfile
    env_file:
      - ./playlist-service/.env
    ports:
      - "8084:8080"
    networks:
      - overlay-network
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  notification-service:
    image: dawidwyskwarski/notification-service:latest
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    env_file:
      - ./notification-service/.env
    ports:
      - "8085:8080"
    networks:
      - overlay-network
    deploy:
      mode: replicated
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  file-service:
    image: dawidwyskwarski/file-service:latest
    build:
      context: .
      dockerfile: ./file-service/Dockerfile
    env_file:
      - ./file-service/.env
    ports:
      - "8083:8080"
    networks:
      - overlay-network
    deploy:
      replicas: 3
      mode: replicated
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

networks:
  overlay-network:
    driver: overlay
