spring.application.name=track-service
server.port=8081

spring.rabbitmq.addresses=${RABBITMQ_URL}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/track_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional connection settings for development purposes:
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
